<div id="content_centered">
	<h1>FAQ - Perguntas frequentes</h1>
	<p><b>O que é esse site? Pra que ele serve?</b></p>
	<p>Este site monitora os tweets enviados no Brasil e em português e identifica os assuntos mais comentados, pessoas mais citadas/retwitadas, palavras mais utilizadas, etc. É como os "trending topics" que o Twitter mostra, mas apenas para os usuários do Twitter no Brasil e com a diferença que as informações exibidas são muito mais detalhadas - tem até gráfico!</p>
	<p><b>Como cê fez isso?</b></p>
	<p>O site coleta uma amostra de tweets em português, de tempos em tempos, e indexa o conteúdo. Os dados vem de um script que usa a busca do Twitter para capturar tweets vindos do Brasil. Como diz um amigo meu, "não é magia, é tecnologia!" :)</p>
	<p>Para mais informaçôes dê uma lida na <a href="http://apiwiki.twitter.com/">documentação da API do Twitter</a>.</p>
	<p><b>Nem todos os tweets em português estão aparecendo no site!</b></p>
	<p>É verdade. Mas o site está otimizado para ler o máximo de tweets que puder com a maior frequência possível, e das últimas vezes que conferi ele andou capturando cerca de 90% do que foi twitado no Brasil. Tweets muito curtos ou em outra língua (como o inglês) é que usualmente não são capturados, mas eu já estou trabalhando para ajustar este problema e em breve ele será corrigido.</p>
	<p>E é bom lembrar que usuários que twitam em português mas que moram em outros países NÃO aparecem no Blablabra. Caso contrário os tweets dos nossos colegas lusófonos de Portugal, por exemplo, iriam se misturar aos nossos.</p>
	<p><b>Meus tweets não aparecem/não são contados pelo site!</b></p>
	<p>No seu perfil do Twitter, no campo "location" (localização), você escreveu sua cidade/estado corretamente? Ou pelo menos escreveu "Brasil"? Sem isto não tem como o Twitter saber de onde você está tuitando, e aí o Blablabra não vai te indexar.</p>
	<p><b>Algumas coisas que apareciam na página principal (como por exemplo os "usuários que mais tuitaram") sumiram de repente.</b></p>
	<p>Quando algum dado some da página principal é porque não há tweets suficientes para calcular aquele dado de forma precisa. Isto normalmente ocorre de madrugada ou em períodos menos movimentados do Twitter.</p>
	<p><b>Por que diabos você fez isso?</b></p>
	<p>Eu queria desenferrujar meu lado programador (eu sou bacharel em Ciência da Computação mas não trabalho diretamente com TI desde 2003) e ter contato com algumas tecnologias que eu nunca conheci a fundo (PHP, APIs públicas, XML, etc). Além do mais eu sempre tive vontade de saber o que os brasileiros andam twittando, mas nunca vi nenhum site ou ferramenta que mostrasse isso.</p>
	<p><b>Desde quando este site está indexando dados?</b></p>
	<p>O lançamento e divulgação "oficiais" do serviço foram em 24/04/09. Os primeiros protótipos do site já haviam começado a indexar dados desde 09/04/09, mas a versão final dos scripts de monitoramento começou a trabalhar pesado mesmo a partir do feriado de Tiradentes (21/04/09).</p>
	<p>Desde então o site mantém no ar uma massa de dados relativa aos últimos 30 dias totalmente livre para consulta. Dados anteriores a isto ficam numa base separada (porque senão a coisa toda ficaria MUITO grande).</p>
	<p><b>Tem como fazer alguma pesquisa mais detalhada no meio dessa timeline? Mudar a escala dos gráficos, voltar mais no tempo, etc?</b></p>
	<p>Sim, mas você terá que falar diretamente comigo: pesquisas mais complexas só se eu escarafunchar a base de dados na unha mesmo.</p>
	<p><b>Cara, gostei (ou odiei) isso, quero te agradecer/xingar/elogiar/pagar uma cerveja/oferecer um emprego/etc.</b></p>
	<p>Você pode me mandar um email (jose.tinoco (arroba) gmail.com) ou <a href="http://twitter.com/oprimo">me procurar no Twitter</a>.</p>
	<small>Agradecimentos aos que me ajudaram com pitacos/dicas/opiniões: <a href="http://twitter.com/be_duarte">@be_duarte</a>, <a href="http://twitter.com/luizzz">@luizzz</a>, <a href="http://twitter.com/muskeetu">@muskeetu</a>, <a href="http://twitter.com/brunomilagres">@brunomilagres</a>, <a href="http://twitter.com/raquelcamargo">@raquelcamargo</a>, <a href="http://twitter.com/renmero">@renmero</a>, <a href="http://twitter.com/bereteando">@bereteando</a>, <a href="http://twitter.com/paulogustavo">@paulogustavo</a>. Valeu!</small>
	<h1>O que andam dizendo sobre o Blablabra</h1>
	<p>- <a href="http://hsm.updateordie.com/autodesenvolvimento/2009/05/post-its-de-domingo-games-sociais-quantum-entanglement-marcas-e-metricas-do-twitter/">O blog da revista HSM Management comenta sobre o Blablabra</a>: "<em>Ali dá para saber quantos replies e retweets sua marca/ empresa (ou você) gera, entre outras coisas</em>".</p>
	<p>- <a href="http://www1.folha.uol.com.br/folha/informatica/ult124u567689.shtml">Matéria da Folha sobre pane no Speedy cita o Blablabra como fonte.</a></p>
	<p>- O Twitcast, podcast brasileiro sobre tudo que acontece no Twitter, <a href="http://www.twitcast.com.br/twitcast/twitcast-5-twitter-brasil-sub-celebridades-politicos-20-e-ferramentas/">falou do Blablabra em seu quinto programa (de 16/07/09)</a>. Além disso, o blog do Twitcast publicou um artigo chamado <a href="http://www.twitcast.com.br/pessoas/buscadores-pessoas/blablabra-assuntos-bombando-fora-da-panelinha/">"Blablabra - Assuntos bombando fora da panelinha"</a>, destacando também que o Blablabra é bom para "sair do nosso nicho" e descobrir assuntos fora do nosso círculo de seguidos/seguidores.</p> 
	<p>- O Blablabra apareceu na TV no programa "A Noite é uma Criança", que passa na Band e é apresentado pelo Otávio Mesquita. <a href="http://vimeo.com/5393751">Assista aqui o trecho do programa onde Rosana Hermann mostra vários sites ligados ao Twitter e, entre eles, mostra o Blablabra</a>.</p>
	<p>- A matéria de capa da <a href="http://www.revistatidigital.com.br/index.php/2009/7">revista TI Digital de julho de 2009</a>, que fala sobre as APIs, menciona o Blablabra e contém, além de uma pequena entrevista com seu criador, um tutorial da API do Google Chart.</p>
	<p>- <a href="http://zerohora.clicrbs.com.br/zerohora/jsp/default2.jsp?uf=1&local=1&source=a2605845.xml&template=3916.dwt&edition=12853&section=1044">O jornal gaúcho Zero Hora publicou nota sobre o Blablabra em sua edição de 05/08</a>.</p>	
	<p>- <a href="http://www.gazetaderibeirao.com.br/conteudo/mostra_noticia.asp?noticia=1632734&area=92020&authent=1665A9DCB01740AFDCA24720AEF9A4">A Gazeta de Ribeirão Preto comenta sobre a força das redes sociais no Brasil e cita o Blablabra:</a> <em>"(...)serve para fazer buscas no Twitter. O usuário pode procurar por palavras-chaves e são mostrados os últimos tweets colocados com essa temática, dando prioridade a páginas brasileiras e em português. O site também quantifica os posts em gráficos que mostram as ocorrências nas últimas duas horas, no último dia e na última semana".</em></p>
	<p>- <a href="http://baguete.com.br/noticiasDetalhes.php?id=3507478">O site baguete.com.br</a> fala do Blablabra como um <em>"serviço de trending topics brasileiro"</em></p>
	<p>- <a href="http://twitter.com/blablabra/favourites">Os favoritos do @blablabra</a> guardam uma pequena coletânea de tweets sobre o site, ditos por gente como @oscarfilho, @betosilva, @malvados e @interney.</p>
</div>